server:
  port: 8019
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/person?useUnicode=true&CharacterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123.com
mybatis:
  mapper-locations: classpath:/mapping/*Mapper.xml
  type-aliases-package: cn.jbit.pojo
logging:
  level:
    web: trace
